### ISSUE TITLE
Huge spam in console

### ISSUE THREAD

**Issue by TheIronMinerLv** [KiwiFisher/MobStacker2#1]
I'm using newest plugin version with newest paperspigot 1.8.8.

This is what spams my console:

11.10 18:26:58 [Server] INFO java.lang.NullPointerException
11.10 18:26:58 [Server] WARN [MobStacker2] Task #2881839 for MobStacker2 v1.4 generated an exception

**Comment by KiwiFisher** [comment]
Hi, thanks for the report.

I am aware of this issue and actively working on it. Any details of what triggers it would be a huge help.

**Comment by KiwiFisher** [comment]
Spam fixed in 1.4.1
