### ISSUE TITLE
[Feature Request] KCauldron Compatibility

### ISSUE THREAD

**Issue by Lmmb74** [KiwiFisher/MobStacker2#2]
Hi, I'm the developer of a forge YT survival and I would like this plugin to be compatible with both vanilla and forge mobs in 1.7.10. That would allow me to fully optimize the server. Before trying to make one, I would like to know if there is a possibility that you add this feature. If so, then I'll be glad to buy your plugin :D. If not, welp, despite of that thanks for taking your time in reading this ;).

**Comment by KiwiFisher** [comment]
Because of the nature of forge I am unable to classify types of forge mobs through  bukkit/spigot, so unfortunately this isn't possible. Sorry about that.

**Comment by Lmmb74** [comment]
No trouble, I tested another plugin (which does not mention forge support in th description) and it worked :D (idk how but it did xD).
