### ISSUE TITLE
Fall Drops Feature

### ISSUE THREAD

**Issue by TheMatrix99s** [KiwiFisher/MobStacker2#4]
Hello, so i am currently working on a full Factions plugin for my server and you did a really good job at your plugin, basically my plugin contains something like when mobs die like zombies they drop a zombie head each one of them, but the problem is when a stacked zombie die by falling it multiply the amount of flesh but only drops 1 head, so i was hoping you would add a feature of multiplying anything they drop.
I am using the latest version of the plugin.

Thanks.

**Comment by KiwiFisher** [comment]
Yes, that would be the case. I am yet to implement functionality using custom loot tables as it is going to be somewhat of a large task. I do not have a time set for completion yet sorry. For now this is not something I can help with, but will be adding support for in the future.
